In [1]:
import torch


In [2]:
t1=torch.tensor(4.)

In [3]:
t1.dtype

torch.float32

In [7]:
t2=torch.tensor([[1.,2.,3.],[5.,6.,7.]])

In [8]:
t2.dtype

torch.float32

In [9]:
t2

tensor([[1., 2., 3.],
        [5., 6., 7.]])

In [12]:
print(t1.shape)
print(t2.shape)

torch.Size([])
torch.Size([2, 3])


Cant create with improper shape and  with differnt datatypes

In [13]:
# t3=torch.tensor([[1.,2.,3.],[4.,5.],[6.]])

ValueError: expected sequence of length 3 at dim 1 (got 2)

In [14]:
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)
x,b,w

(tensor(3.), tensor(5., requires_grad=True), tensor(4., requires_grad=True))

In [16]:
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [17]:
y.backward()

In [18]:
print("dy/dx",x.grad)
print("dy/dw",w.grad)
print("dy/db",b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


In [20]:
t5=torch.full([3,2],42)
t5

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [22]:
t6=t5.reshape(2,3)
t6

tensor([[42, 42, 42],
        [42, 42, 42]])

In [23]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=torch.from_numpy(x)
z=y.numpy()
x.dtype,y.dtype,z.dtype

(dtype('int64'), torch.int64, dtype('int64'))