In [ ]:
import torch
import numpy as np

In [ ]:
x=torch.empty(3,2)
x

tensor([[2.8026e-45, 0.0000e+00],
        [2.8026e-45, 1.4013e-45],
        [3.3631e-44, 4.5632e-41]])

In [ ]:
x=torch.rand(2,2)
x

tensor([[0.7578, 0.5692],
        [0.6006, 0.1483]])

In [ ]:
x=torch.zeros(1,2)
x

tensor([[0., 0.]])

In [ ]:
x=torch.ones(3,4,dtype=torch.int)
print(x,x.dtype)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32) torch.int32


In [ ]:
y=torch.tensor([2,3,4,5])
y

tensor([2, 3, 4, 5])

In [ ]:
x=torch.tensor([1,2,3])
y=torch.tensor([4,5,6])
y.add_(x)     #inplace addition
print(x,y)

tensor([1, 2, 3]) tensor([5, 7, 9])


In [ ]:
x=torch.tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
print(x[1,:])
print(x[:,1])

tensor([1, 1, 1, 1], dtype=torch.int32)
tensor([1, 1, 1], dtype=torch.int32)


In [ ]:
y=x.view(12)
print(y)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=torch.int32)


In [ ]:
a=torch.tensor([1,2,4,5])
b=a.numpy()
a+=1
print(a,a.dtype)
print(b,b.dtype)

tensor([2, 3, 5, 6]) torch.int64
[2 3 5 6] int64


In [ ]:
a=np.ones(5)
b=torch.from_numpy(a)
a+=1
print(a,a.dtype)
print(b,b.dtype)

[2. 2. 2. 2. 2.] float64
tensor([2., 2., 2., 2., 2.], dtype=torch.float64) torch.float64


In [ ]:
# if torch.cuda.is_available():
#   device=torch.device('cuda')
#   a=torch.ones(5,device=device)
#   b=a.numpy()
#   a+=1
#   print(a,a.dtype)
#   print(b,b.dtype)

# `AUTOGRAD

In [ ]:
x=torch.ones(4,requires_grad=True)
x

tensor([1., 1., 1., 1.], requires_grad=True)

In [ ]:
y=x+2
y

tensor([3., 3., 3., 3.], grad_fn=<AddBackward0>)

In [ ]:
z=x*3
z

tensor([3., 3., 3., 3.], grad_fn=<MulBackward0>)

In [ ]:
# z.backward()
z=z.mean()
z.backward()


In [ ]:
x.grad

tensor([1.5000, 1.5000, 1.5000, 1.5000])

Preventing gradient from backward operation

In [ ]:
# x.requires_grad_(False)
# x.detach
# with torch.no_grad()

tensor([1., 1., 1., 1.])

In [ ]:
# # z.backward()
# z=z.mean()
# z.backward()

# x.grad

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [ ]:
weights=torch.rand(3,requires_grad=True)
for epoch in range(4):
  model_output=(weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])


Backward Propagation

In [ ]:
import torch


In [ ]:
x=torch.tensor(1.0)
w=torch.tensor(1.0,requires_grad=True)
y=torch.tensor(2.0)

#forward pass
y_hat=w*x
loss=(y_hat-y)**2
print(loss)

#backwardpass
loss.backward()
print(w.grad)

#forward pass
y_hat=w*x
loss=(y_hat-y)**2
print(loss)

#backwardpass
loss.backward()
print(w.grad)


tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)
tensor(1., grad_fn=<PowBackward0>)
tensor(-4.)
